[Icon Theme]
Name=Lizarbe-Red

Comment=Lizarbe Red File Manager Icon Theme
DisplayDepth=32

Inherits=Yaru-red,Yaru,breeze-dark,Adwaita,hicolor

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

KDE-Extensions=.svg

########## Directories
########## File manager places, mimetypes and sidebar devices

Directories=places/16,places/22,places/32,places/48,places/64,places/96,places/128,places/scalable,places/symbolic,devices/symbolic,mimetypes/16,mimetypes/22,mimetypes/32,mimetypes/48,mimetypes/64,mimetypes/96,mimetypes/128,mimetypes/scalable
ScaledDirectories=places/16@2x,places/22@2x,mimetypes/16@2x,mimetypes/22@2x

########## Mimetypes
########## ordered by size

#16x16 - Fixed size - For small file type icons
[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed
MinSize=16

#16x16@2x - Fixed size - For small file type icons
[mimetypes/16@2x]
Size=16
Scale=2
Context=MimeTypes
Type=Fixed
MinSize=16

#22x22 - Scalable size - For small file type icons
[mimetypes/22]
Size=22
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

#22x22@2x - Scalable size - For small file type icons
[mimetypes/22@2x]
Size=22
Scale=2
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

#32x32 - Fixed size - For file type icons
[mimetypes/32]
Size=32
Context=MimeTypes
Type=Fixed

#48x48 - Scalable - For file type icons
[mimetypes/48]
Size=48
Context=MimeTypes
Type=Scalable
MinSize=32
MaxSize=64

#64x64 - Fixed size - For file type icons
[mimetypes/64]
Size=64
Context=MimeTypes
Type=Fixed

#96x96 - Fixed size - For file type icons
[mimetypes/96]
Size=96
Context=MimeTypes
Type=Fixed

#128x128 - Fixed size - For file type icons
[mimetypes/128]
Size=128
Context=MimeTypes
Type=Fixed

#scalable - Scalable - For file type icons at any size
[mimetypes/scalable]
Size=96
Context=MimeTypes
Type=Scalable
MinSize=32
MaxSize=512

########## Places
########## ordered by size

#16x16 - Fixed size - For small folder icons
[places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

#16x16@2x - Fixed size - For small folder icons
[places/16@2x]
Size=16
Scale=2
Context=Places
Type=Fixed
MinSize=16

#22x22 - Fixed size
[places/22]
Size=22
Context=Places
Type=Fixed

#22x22@2x - Fixed size
[places/22@2x]
Size=22
Scale=2
Context=Places
Type=Fixed

#32x32 - Fixed size - For folder icons
[places/32]
Size=32
Context=Places
Type=Fixed

#48x48 - Scalable - For folder icons
[places/48]
Size=48
Context=Places
Type=Scalable
MinSize=32
MaxSize=64

#64x64 - Fixed size - For folder icons
[places/64]
Size=64
Context=Places
Type=Fixed

#96x96 - Fixed size - For folder icons
[places/96]
Size=96
Context=Places
Type=Fixed

#128x128 - Fixed size - For folder icons
[places/128]
Size=128
Context=Places
Type=Fixed

#scalable - Scalable - For folder icons at any size
[places/scalable]
Size=96
Context=Places
Type=Scalable
MinSize=32
MaxSize=512

########## Symbolic (Gnome / Nautilus Sidebar)

[places/symbolic]
Context=Places
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[devices/symbolic]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable

########## EOF
