[Icon Theme]
Name=Dedicated-to-Hackerer-Red
Inherits=Anubis,ePapirus,Humanity,Adwaita,Mint-X,hicolor

Example=x-directory-normal


Directories=actions/16,actions/22,actions/32,apps/scalable,categories/scalable,devices/scalable,emblems/scalable,mimetypes/scalable,places/16,places/scalable,status/scalable

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed

[apps/scalable]
Size=64
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[categories/scalable]
Context=Categories
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[devices/scalable]

Size=64
Context=Actions
Type=Scalable
MinSize=16
MaxSize=128

[emblems/scalable]
Size=64
Context=Actions
Type=Scalable
MinSize=16
MaxSize=128

[mimetypes/scalable]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[places/16]
Size=16
Context=Places
Type=Fixed

[places/scalable]
Context=Places
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[status/scalable]
Context=Status
Size=64
MinSize=8
MaxSize=512
Type=Scalable
