mode = "dark"

accent = "#E31B23"
selection = "#E31B23"
muted = "#444444"

background = "#08080B"
dark_background = "#050507"
darker_background = "#000000"
lighter_background = "#1a1a1a"

foreground = "#d8d8d8"
dark_foreground = "#585858"
light_foreground = "#ececec"
bright_foreground = "#ffffff"

hyprland_active_border = "#E31B23"
hyprland_inactive_border = "#1c1c1c"

red = "#E31B23"
yellow = "#E5A83B"
orange = "#E05A2B"
green = "#2DB872"
cyan = "#45A0B5"
blue = "#5A7DA8"
magenta = "#B85478"
brown = "#5E2222"

bright_red = "#FF333D"
bright_yellow = "#F5B743"
bright_green = "#42D98D"
bright_cyan = "#68BFD8"
bright_blue = "#7A9FCB"
bright_magenta = "#D47098"
