[controls]
normal-color        = "#E31B23"
normal-fill-alpha   = 0.08
normal-border       = "#E31B23"
normal-border-width = 1
normal-border-alpha = 0.4

hover-cursor-color        = "#FF333D"
hover-cursor-fill-alpha   = 0.15
hover-cursor-border       = "#FF333D"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.5

selected-color        = "#E31B23"
selected-fill-alpha   = 0.25
selected-border       = "#E31B23"
selected-border-width = 1
selected-border-alpha = 1.0
